services:
  icad_dispatch:
    image: thegreatcodeholio/icad_dispatch:latest
    depends_on:
      - redis
      - mysql
    env_file:
      - .env
    ports:
      - "9911:9911"
    volumes:
      - ${WORKING_PATH}/log:/app/log
      - ${WORKING_PATH}/etc:/app/etc
  redis:
    image: redis:7.4.2
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:9.1
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./docker_init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8086:80"

volumes:
  redis_data:
  mysql_data: